<?php

/**
 * @file
 * Primary module hooks for Druki - Vue.js module.
 */

/**
 * Implements hook_library_info_alter().
 */
function druki_vue_library_info_alter(&$libraries, $extension) {
  if ($extension != 'druki_vue') {
    return;
  }

  // Use unminified version only for development environment.
  if (getenv('ENV') == 'development') {
    unset($libraries['vuejs']['js']);
    $libraries['vuejs']['js']['/libraries/vue/dist/vue.js'] = [];
  }
}
