<?php

/**
 * @file
 * Provides a druki content entity type.
 */

use Drupal\Core\Block\BlockPluginInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\StringTranslation\TranslatableMarkup;

/**
 * Implements hook_theme().
 */
function druki_content_theme(): array {
  return [
    'druki_content' => [
      'render element' => 'elements',
      'file' => 'druki_content.theme.inc',
    ],
    'druki_content_edit_form' => [
      'render element' => 'form',
    ],
    'druki_content_toc' => [
      'variables' => [
        'druki_content' => NULL,
      ],
      'file' => 'druki_content.theme.inc',
    ],
    'druki_content_category_navigation' => [
      'variables' => [
        'links' => [],
      ],
      'file' => 'druki_content.theme.inc',
    ],
    'druki_content_help_and_feedback' => [
      'variables' => [
        'edit_url' => NULL,
        'improve_url' => NULL,
        'help_url' => NULL,
      ],
    ],
    'druki_content_next_prev' => [
      'variables' => [
        'prev_link' => NULL,
        'next_link' => NULL,
      ],
    ],
    'druki_content_element_text' => [
      'variables' => [
        'content' => NULL,
      ],
    ],
    'druki_content_element_heading' => [
      'variables' => [
        'level' => NULL,
        'content' => NULL,
      ],
    ],
    'druki_content_element_code' => [
      'variables' => [
        'content' => NULL,
      ],
    ],
    'druki_content_element_aside' => [
      'variables' => [
        'aside_type' => NULL,
        'content' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_block_view_BASE_BLOCK_ID_alter().
 */
function druki_content_block_view_druki_category_navigation_alter(array &$build, BlockPluginInterface $block): void {
  $build['#configuration']['label'] = $block->label();
}

/**
 * Implements hook_entity_base_field_info().
 *
 * @todo Move to 'druki_redirect' when module will be enabled and deployed.
 */
function druki_content_entity_base_field_info(EntityTypeInterface $entity_type): array {
  $fields = [];
  if ($entity_type->id() == 'redirect') {
    $fields['druki_content_redirect'] = druki_content_redirect_druki_content_redirect_base_field();
  }
  return $fields;
}

/**
 * Gets definition for redirects 'druki_content_redirect' field.
 *
 * @return \Drupal\Core\Field\BaseFieldDefinition
 *   The field definition.
 *
 * @todo Move to 'druki_redirect' when module will be enabled and deployed.
 */
function druki_content_redirect_druki_content_redirect_base_field(): BaseFieldDefinition {
  return BaseFieldDefinition::create('boolean')
    ->setLabel(new TranslatableMarkup('Used by druki content'))
    ->setDescription(new TranslatableMarkup('Indicates whether the redirect is created automatically.'))
    ->setDefaultValue(FALSE);
}
