<?php

/**
 * @file
 * Provides a druki content entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function druki_content_theme() {
  return [
    'druki_content' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for druki content templates.
 *
 * Default template: druki-content.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the druki content information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_druki_content(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_cron().
 */
function druki_content_cron() {
  // Clean missing content from database.
  \Drupal::service('entity_type.manager')
    ->getStorage('druki_content')
    ->deleteMissing();
}
