<?php

/**
 * @file
 * Provides a druki content entity type.
 */

use Drupal\Core\Block\BlockPluginInterface;

/**
 * Implements hook_theme().
 */
function druki_content_theme(): array {
  return [
    'druki_content' => [
      'render element' => 'elements',
      'file' => 'druki_content.theme.inc',
    ],
    'druki_content_edit_form' => [
      'render element' => 'form',
    ],
    'druki_content_toc' => [
      'variables' => [
        'druki_content' => NULL,
      ],
      'file' => 'druki_content.theme.inc',
    ],
    'druki_content_category_navigation' => [
      'variables' => [
        'links' => [],
      ],
      'file' => 'druki_content.theme.inc',
    ],
    'druki_content_help_and_feedback' => [
      'variables' => [
        'edit_url' => NULL,
        'improve_url' => NULL,
        'help_url' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_block_view_BASE_BLOCK_ID_alter().
 */
function druki_content_block_view_druki_category_navigation_alter(array &$build, BlockPluginInterface $block) {
  $build['#configuration']['label'] = $block->label();
}
