<?php

/**
 * @file
 * Primary module hooks for Druki module.
 */

use Drupal\imagemagick\ImagemagickExecArguments;

/**
 * Implements hook_preprocess_HOOK().
 */
function druki_preprocess_toolbar(array &$variables): void {
  $variables['#attached']['library'][] = 'druki/druki.toolbar';
}

/**
 * Implements hook_cron().
 */
function druki_cron(): void {
  \Drupal::service('druki.cron.check_drupal_releases')->process();
}

/**
 * Implements hook_preprocess_HOOK() for 'page--front.html.twig'.
 */
function druki_preprocess_page__front(array &$variables): void {
  $variables['drupal_versions'] = [
    '#theme' => 'druki_drupal_versions',
  ];
}

/**
 * Implements hook_theme().
 */
function druki_theme($existing, $type, $theme, $path) {
  return [
    'druki_drupal_versions' => [
      'variables' => [],
      'file' => 'druki.theme.inc',
    ],
    'druki_card' => [
      'variables' => [
        'title' => NULL,
        'subhead' => NULL,
        'description' => NULL,
        'actions' => [],
        'primary_url' => NULL,
      ],
      'file' => 'druki.theme.inc',
    ],
    'druki_header_search' => [
      'variables' => [
        'default_value' => '',
      ],
    ],
    'druki_official_user_guide' => [
      'variables' => [],
      'file' => 'druki.theme.inc',
    ],
  ];
}

/**
 * Implements hook_imagemagick_arguments_alter().
 */
function druki_imagemagick_arguments_alter(ImagemagickExecArguments $arguments, $command) {
  // https://developers.google.com/speed/docs/insights/OptimizeImages
  $arguments->add('-sampling-factor 4:2:0');
  // Progression JPEG and interlaced PNG's support.
  $arguments->add('-interlace Plane');
  // Clean image for all unused data. I.e. EXIF.
  $arguments->add('-strip');
}

/**
 * Implements hook_preprocess_HOOK() for 'html.html.twig'.
 */
function druki_preprocess_html(array &$variables): void {
  $variables['#attached']['library'][] = 'druki/instant-page';
  // Make instant.page library prefetch link in viewport instead of touch.
  $variables['attributes']['data-instant-intensity'] = 'viewport';
}

/**
 * Implements hook_preprocess_HOOK() for 'responsive-image.html.twig'.
 */
function druki_preprocess_responsive_image(array &$variables) {
  $variables['img_element']['#attributes']['loading'] = 'lazy';
  $variables['img_element']['#attributes']['decoding'] = 'async';
}

/**
 * Implements hook_preprocess_HOOK() for 'image.html.twig'.
 */
function druki_preprocess_image(array &$variables) {
  $variables['attributes']['loading'] = 'lazy';
  $variables['attributes']['decoding'] = 'async';
}
