<?php

/**
 * @file
 * Primary module hooks for Druki module.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function druki_preprocess_toolbar(array &$variables): void {
  $variables['#attached']['library'][] = 'druki/druki.toolbar';
}

/**
 * Implements hook_cron().
 */
function druki_cron(): void {
  $request_time = \Drupal::time()->getRequestTime();
  $drupal_releases = \Drupal::state()->get('druki.drupal_releases', [
    'expires' => 0,
    'last_stable_release' => NULL,
    'last_minor_release' => NULL,
  ]);

  if ($request_time > $drupal_releases['expires']) {
    // Trying to get new last stable release for Drupal project.
    /** @var \Drupal\druki\Service\DrupalProjects $drupal_projects */
    $drupal_projects = \Drupal::service('druki.drupal_projects');
    $stable_version = $drupal_projects->getCoreLastStableVersion();
    $minor_version = $drupal_projects->getCoreLastMinorVersion();

    // If release can't be retrieved, we skip everything else and wait for next
    // cron to try again.
    if ($stable_version && $minor_version) {
      $drupal_releases['last_stable_release'] = $stable_version;
      $drupal_releases['last_minor_release'] = $minor_version;
      $drupal_releases['expires'] = $request_time + (60 * 60 * 24);
      \Drupal::state()->set('druki.drupal_releases', $drupal_releases);

      /** @var \Drupal\Core\Cache\CacheTagsInvalidatorInterface $cache_tags_invalidator */
      $cache_tags_invalidator = \Drupal::service('cache_tags.invalidator');
      // Invalidate all caches which uses last stable release value.
      $cache_tags_invalidator->invalidateTags(['druki_last_stable_release']);
    }
  }
}

/**
 * Implements hook_preprocess_HOOK() for page.html.twig.
 */
function druki_preprocess_page__front(array &$variables): void {
  $variables['drupal_versions'] = [
    '#theme' => 'druki_drupal_versions',
    '#cache' => [
      'tags' => ['druki_last_stable_release'],
    ],
  ];
}

/**
 * Implements hook_theme().
 */
function druki_theme($existing, $type, $theme, $path) {
  return [
    'druki_drupal_versions' => [
      'variables' => [],
      'file' => 'druki.theme.inc',
    ],
  ];
}
