condition.plugin.druki_content:
  type: condition.plugin
  label: 'Druki Content condition'

field.value.druki_category:
  type: mapping
  label: Default value
  mapping:
    area:
      type: string
      label: Area
    order:
      type: integer
      label: Order
    title:
      type: string
      label: Category title

druki_content.content_source_settings:
  type: config_object
  label: 'Druki content source Settings'
  mapping:
    repository_uri:
      type: string
      label: 'Repository local URI'
    repository_url:
      type: string
      label: 'Repository remote URL'
