<?php

/**
 * @file
 * Primary module hooks for Druki - Media module.
 */

/**
 * Implements hook_theme().
 */
function druki_media_theme(array $existing, string $type, string $theme, string $path): array {
  return [
    'druki_media_remote_video_optimized' => [
      'variables' => [
        'thumbnail_uri' => NULL,
        'thumbnail_style' => 'thumbnail',
        'thumbnail_alt' => '',
        'video_provider' => NULL,
        'video_id' => NULL,
      ],
      'file' => 'druki_media.theme.inc',
    ],
  ];
}
