<?php

/**
 * @file
 * Primary module hooks for Druki - Files module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function druki_file_file_presave(EntityInterface $entity) {
  /** @var \Drupal\druki_file\Service\DrukiFileTracker $file_tracker */
  $file_tracker = \Drupal::service('druki_file.tracker');

  try {
    $file_tracker->track($entity);
  }
  catch (Exception $e) {
    \Drupal::service('logger.channel.druki_file')
      ->error('Problems with file hash creation. File ID: @fid.', [
        '@fid' => $entity->id()
      ]);
  }
}

/**
 * Implements hook_entity_base_field_info().
 */
function druki_file_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];

  if ($entity_type->id() === 'file') {
    // Add field for store file hash.
    $fields['druki_file_hash'] = BaseFieldDefinition::create('string')
      ->setLabel(t('File hash'))
      ->setDescription(t('The file md5 hash.'))
      ->setSetting('max_length', 255);
  }

  return $fields;
}
