druki.official_user_guide_settings:
  type: config_object
  label: 'Official user guide settings'
  mapping:
    image_style:
      type: string
      label: 'Image style'

druki.frontpage.settings:
  type: config_object
  label: 'Frontpage settings'
  mapping:
    download:
      image_style:
        type: string
        label: 'Image style'
