druki.official_user_guide_settings:
  type: config_object
  label: 'Official user guide settings'
  mapping:
    image:
      type: mapping
      label: 'Image'
      mapping:
        media:
          type: string
          label: 'Media ID'
        style:
          type: string
          label: 'Image style'

