<?php

/**
 * @file
 * Provides custom hooks implementations and functions.
 */

declare(strict_types=1);

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\StringTranslation\TranslatableMarkup;

/**
 * Implements hook_entity_base_field_info().
 */
function druki_redirect_entity_base_field_info(EntityTypeInterface $entity_type): array {
  $fields = [];
  if ($entity_type->id() == 'redirect') {
    $fields['druki_redirect'] = druki_redirect_redirect_druki_redirect_base_field();
  }
  return $fields;
}

/**
 * Gets definition for redirects 'druki_redirect' field.
 *
 * @return \Drupal\Core\Field\BaseFieldDefinition
 *   The field definition.
 */
function druki_redirect_redirect_druki_redirect_base_field(): BaseFieldDefinition {
  return BaseFieldDefinition::create('boolean')
    ->setLabel(new TranslatableMarkup('Used by druki redirect'))
    ->setDescription(new TranslatableMarkup('Indicates whether the redirect is created automatically.'))
    ->setDefaultValue(FALSE);
}
