<?php

/**
 * @file
 * Primary module hooks for Druki - Search module.
 */

use Drupal\druki_search\SearchPage\FilterForm;
use Drupal\druki_search\SearchPage\QueryHelper;
use Drupal\search_api\Query\QueryInterface;

/**
 * Implements hook_theme().
 */
function druki_search_theme($existing, $type, $theme, $path) {
  return [
    'druki_search_result' => [
      'variables' => [
        'title' => NULL,
        'url' => NULL,
        'display_url' => NULL,
        'supporting_text' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_search_api_query_alter().
 */
function druki_search_search_api_query_alter(QueryInterface $query) {
  if (!$query->getIndex()->getServerInstance()->supportsFeature('search_api_facets')) {
    return;
  }

  if ($query->getSearchId() == QueryHelper::FILTERED) {
    FilterForm::alterQuery($query);
  }
}
