<?php

/**
 * @file
 * Primary module hooks for Druki - Search module.
 */

use Drupal\druki_search\SearchPage\FilterForm;

/**
 * Implements hook_theme().
 */
function druki_search_theme($existing, $type, $theme, $path) {
  return [
    'druki_search_result' => [
      'variables' => [
        'title' => NULL,
        'url' => NULL,
        'display_url' => NULL,
        'supporting_text' => NULL,
      ],
    ],
  ];
}
