name: Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ develop ]

env:
  COMPOSER_FLAGS: '--ansi --no-interaction --no-progress --no-suggest --prefer-dist'
  CODECOV_TOKEN: ${{ secrets.ci_codecov_token }}

jobs:
  phpcs:
    name: 'PHPCS'
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-version:
          - '8.0'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'

      - name: 'Install PHP'
        uses: 'shivammathur/setup-php@v2'
        with:
          coverage: 'none'
          extensions: 'intl, zip, intl, zip, date, dom, filter, gd, hash, json, pcre, pdf, session, simplexml, spl, tokenizer, xml'
          ini-values: 'memory_limit=-1'
          php-version: ${{ matrix.php-version }}

      - name: 'Determine composer cache directory'
        id: 'determine-composer-cache-directory'
        run: echo "::set-output name=directory::$(composer config cache-dir)"

      - name: 'Cache dependencies installed with composer'
        uses: 'actions/cache@v2'
        with:
          path: ${{ steps.determine-composer-cache-directory.outputs.directory }}
          key: php-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: php-${{ matrix.php-version }}

      - name: 'Install Composer dependencies'
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install $COMPOSER_FLAGS

      - name: 'PHPCS Analyse'
        run: vendor/bin/phpcs

  phpstan:
    name: 'PHPStan'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - '8.0'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'

      - name: 'Install PHP'
        uses: 'shivammathur/setup-php@v2'
        with:
          coverage: 'none'
          extensions: 'intl, zip, intl, zip, date, dom, filter, gd, hash, json, pcre, pdf, session, simplexml, spl, tokenizer, xml'
          ini-values: 'memory_limit=-1'
          php-version: ${{ matrix.php-version }}

      - name: 'Determine composer cache directory'
        id: 'determine-composer-cache-directory'
        run: echo "::set-output name=directory::$(composer config cache-dir)"

      - name: 'Cache dependencies installed with composer'
        uses: 'actions/cache@v2'
        with:
          path: ${{ steps.determine-composer-cache-directory.outputs.directory }}
          key: php-${{ matrix.php-version }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: php-${{ matrix.php-version }}

      - name: 'Install Composer dependencies'
        if: steps.composer-cache.outputs.cache-hit != 'true'
        run: composer install $COMPOSER_FLAGS

      - name: 'PHPStan Analyse'
        run: vendor/bin/phpstan analyse --configuration=phpstan.neon

  phpunit:
    name: 'PHPUnit'
    runs-on: ubuntu-latest
    needs:
      - phpstan
      - phpcs
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'

      - name: 'Copy files for environment'
        run: |
          cp ./.github/workflows/d4d-phpunit/.env ./.env
          cp ./.github/workflows/d4d-phpunit/docker-compose.yml ./docker-compose.yml
          cp ./.github/workflows/d4d-phpunit/settings.php ./web/sites/default/settings.php
          mkdir -p ./web/sites/default/files/druki-content-source

      - name: 'Run docker'
        run: "docker-compose up -d"

      - name: 'Install site dependencies'
        run: "docker-compose exec -T php composer install"

      - name: 'Install website'
        run: 'docker-compose exec -T php drush site:install druki_installer'

      - name: 'Run tests'
        run: 'docker-compose exec -T php ./vendor/bin/phpunit --coverage-clover coverage.xml --coverage-text'

      - name: 'Upload code coverage'
        run: 'bash <(curl -s https://codecov.io/bash)'
